### ISSUE TITLE
Add this as an official installation method

### ISSUE THREAD

**Issue by manuel-rw** [Wiggen94/ha-homarr-server#1]
Hello,
maintainer of Homarr here 👋.
I saw your project here by coincidence.
I think it would be great to add this to the official https://homarr.dev documentation as an official installation method as long as you'd volunteer to keep it somewhat up to date with HomeAssistant.
I personally don't use Supervised HomeAssistant but I'm sure that some people will love this easy to use solution.
Sorry for contacting you via this issue - I didn't find any other means of contact on your profile.
Cheers 🥂

**Comment by Wiggen94** [comment]
Absolutely, I've added a way to contact me on my profile now via email. I also think I've messaged you on discord now.
