### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by brusarp** [Wiggen94/ha-homarr-server#2]
Hi,
I succesfully installed Homarr with your method... Now there's a new version of Homarr available. How I can update it?
![image](https://github.com/Wiggen94/ha-homarr-server/assets/14950532/bbe5f045-6e94-48a5-8b50-c6c0af0c920b)

**Comment by Wiggen94** [comment]
EDIT: I misread your question.
![image](https://github.com/Wiggen94/ha-homarr-server/assets/13270464/b3f64f5b-1c32-4d3d-823a-9e59e429d7b8)

Go to addons, then homarr and hit rebuild

**Comment by brusarp** [comment]
Good, thank you!
Better to add this hint into instructions 😉👍

**Comment by Wiggen94** [comment]
Good idea, added! 👍
