### ISSUE TITLE
Where is config file for Homarr in Home Assistant Add-On

### ISSUE THREAD

**Issue by ArtCodesArt** [Wiggen94/ha-homarr-server#3]
# Background
- Using Homarr as Home Assistant Add-On, installed using instructions from: https://homarr.dev/docs/getting-started/installation#home-assistant-add-on

# Problem
1. How to backup Homarr dashboards ?

According to the following links below there used to be a backup feature that has now been removed. However, the posts suggest that a config file should still do the job.

- https://github.com/ajnart/homarr/issues/1659#issuecomment-1814621387
- https://www.answeroverflow.com/m/1173057799455002674

Home Assistant (HA) will usually create a folder under `custom_components` and I don't see any reference to this add-on in HA.

I can't seem to locate the config file in Home Assistant for the dashboards, any way to backup Homarr when running it in HA?

**Comment by Wiggen94** [comment]
Hey! 
`Your files are safely backed up to /share in your Home Assistant installation.`
So you could use your preferred way to access that shared directory. I prefer using smb myself.

**Comment by ramos45** [comment]
> Hey! `Your files are safely backed up to /share in your Home Assistant installation.` So you could use your preferred way to access that shared directory. I prefer using smb myself.

how can i restore it? i think that the file in /share it`s only a backup. nothing happened if i edit it
