### ISSUE TITLE
Container logging spam

### ISSUE THREAD

**Issue by manonstreet** [Wiggen94/ha-homarr-server#5]
Brand new install of add-on.  Log shows:

Exporting hostname...
Migrating database...
yarn run v1.22.19
$ tsx ./migrate.ts
Done in 0.66s.
Starting production server...
Listening on port 7575 url: http://3b7f9a0a-homarr-addon:7575
ℹ Instance is using a database on the file system. Checking if file '/data/db.sqlite' is writable...
ℹ Database is writeable
ℹ Instance is using a database on the file system. Checking if file '/data/db.sqlite' is writable...
ℹ Database is writeable
ℹ Instance is using a database on the file system. Checking if file '/data/db.sqlite' is writable...
ℹ Database is writeable
ℹ Instance is using a database on the file system. Checking if file '/data/db.sqlite' is writable...
ℹ Database is writeable
...

Log message repeats forever ever few seconds.  Is this expected?

**Comment by Wiggen94** [comment]
This is expected behaviour and is present in the standard container image as well. It is not something that has been added by this project.
